### PR TITLE
Fix for `Unparenthesized a ? b : c ? d : e` error

### LINKED ISSUE #103: FatalError: Unparenthesized `a ? b : c ? d : e` is not supported
Just upgraded to the latest version and I'm getting this error:

```
Symfony\Component\ErrorHandler\Error\FatalError: Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)`
  File "/vendor/ringcentral/ringcentral-php/src/Platform/Platform.php", line 201
```

I'll try and get a PR submitted, but for now just trying to revert to the previous version since this breaks things completely!

### PR DESCRIPTION
**Pull request by manavo**
Fixes #103

### CODE REVIEW

**Comment by manavo** [comment]
Due to the ambiguity and the issue itself, I'm assuming that the parentheses I've added keeps the intended order. Can't be 100% sure though (and I guess that's why PHP doesn't like it either)

**Review by jvrsolis — APPROVED** [review]

**Comment by spintokha** [comment]
Hi @jvrsolis, could you accept PR, please?

**Comment by RomanDeNu** [comment]
Please accept this PR.

**Comment by manavo** [comment]
Is there anything I need to do for this contribution to be accepted? The contributing.md file doesn’t seem to suggest so, but if that’s the case let me know, or can you just add the parentheses directly and close this?

**Comment by AndrewMonty** [comment]
+1 for this fix. Upgraded to PHP 8 and started getting this error, but can't downgrade the package because I'm using JWT auth...

**Pull request merged**
