### PR TITLE
Add laravel 8 support with Guzzle 7 and fix tests for all php versions

### PR DESCRIPTION
**Pull request by coxlr**
Add support for Laravel 8 with Guzzle 7.

Also fixed tests for all PHP versions and added GitHub workflow to run tests on push and pull requests.

### CODE REVIEW

**Comment by coxlr** [comment]
Is it possible to get this merged?

**Comment by kirill-konshin** [comment]
No need for Github action, Travis does it's job just fine. Please remove it and I will merge & release.

**Comment by kirill-konshin** [comment]
Also what was the point to replace annotations?

**Comment by kirill-konshin** [comment]
Also tests failed in Travis.

**Comment by coxlr** [comment]
Great thanks. I have removed the GitHub actions. The tests were also previously failing in travis in the current verion. I have fixed the actual tests for the used php version and tested using the GitHub actions that I initially added were they all pass. 

ThI believe the current failing in travis is due to the PHP version that runs on travis-ci was compiled with gnutls-cli (GnuTLS) 2.12.23, from 2011. This specific version of gnutls-cli has problems with some (but not all) TLS 1.2 connections. See: https://stackoverflow.com/questions/38375211/curl-error-35-gnutls-handshake-failed

The @ExpectedException, @expectedExceptionCode, @expectedExceptionMessage, and @expectedExceptionMessageRegExp annotations are deprecated and removed in PHPUnit 9.

**Comment by coxlr** [comment]
I have fixed the travis tests, it looks like the issue with PHP 7.1 is something they are aware of, there is an open issue for it: https://github.com/travis-ci/travis-ci/issues/6339
Setting the PHP version to 7.1.18 allows the tests to successfully run and pass for PHP 7.1. I also added PHP 7.4 to the matrix.

**Comment by coxlr** [comment]
Is there anything else I can do, or help with to get this merged?

**Comment by kirill-konshin** [comment]
Merged & published. Thank you.

**Pull request merged**
