### PR TITLE
Add Laravel 10 support with PubNub 6

### LINKED ISSUE #117: Upgrade PubNub dependency
PubNub is currently set to `^4.7.0`, but PubNub is up to `^6.0.0`.

Trying to update it seems to mostly work, other than requiring a UUID to be set:

```
PubNub\Exceptions\PubNubConfigurationException: UUID should not be empty

/Users/manavo/Code/ringcentral-php/vendor/pubnub/pubnub/src/PubNub/PubNub.php:115
/Users/manavo/Code/ringcentral-php/vendor/pubnub/pubnub/src/PubNub/PubNub.php:89
/Users/manavo/Code/ringcentral-php/src/Subscription/Subscription.php:408
/Users/manavo/Code/ringcentral-php/src/Subscription/Subscription.php:240
/Users/manavo/Code/ringcentral-php/src/Subscription/Subscription.php:154
/Users/manavo/Code/ringcentral-php/src/Subscription/SubscriptionTest.php:107
```

Adding a UUID [here](https://github.com/ringcentral/ringcentral-php/blob/master/src/Subscription/Subscription.php#L404) makes the tests pass, but I'm guessing the point would be to have a UUID set, persisted, and then reused, for each device/client.

Not that familiar with PubNub, so a bit reluctant to start a PR for this.

### PR DESCRIPTION
**Pull request by coxlr**
Add Laravel 10 support by using PubNub 6 which uses Monolog 3.x

fixes #117

### CODE REVIEW

**Comment by coxlr** [comment]
Is it possible to get this merged? Or is there anything else you would like me to update or change?

**Comment by JosephLeedy** [comment]
Any updates on this?

**Comment by coxlr** [comment]
@byrnereese apologies for the ping, but wondering if you would be able to get this merged, or let me know if is there anything else you would like me to update or change?

**Comment by byrnereese** [comment]
Thank you so much for pinging me. Let me see if I can get some help reviewing this.

**Comment by tylerlong** [comment]
Please help me to understand the issue: what is the error for the current stable version to work with Laravel 10?  Is PubNub 4.x not compatible with Laravel 10?

**Comment by coxlr** [comment]
@tylerlong thanks for looking in to this. That is correct, PubNub 4.0.0-alpha is the last version to be compatible with Laravel 10, due to Laravel 10 (the latest version) requiring monolog ^3.0, therefore the last compatible version of ringcentral-php is 2.2.5, as ^2.3.0 requires pubnub ^4.7.0 which use monolog ^1.1|^2.0. pubnub 6.0.0 added support for monolog ^3.0 which makes it compatible with Laravel 10. 
So for the latest version of ringcentral-php to be compatible with Laravel 10 it needs to support pubnub ^6.0.0, which is what this pull request aims to achieve.

**Comment by tylerlong** [comment]
I am not a PHP developer. 
But I can merge this PR after review and testing.

There is one issue:
According to https://www.pubnub.com/docs/sdks/php/api-reference/configuration
There is no `setUuid`, it should be `setUserId`?

And this id should not the device ID/extension ID instead of a hard-coded string.
But I guess a hard-coded string will work since version PubNub 4.x doesn't provide all at all.
I would suggest to use `subscription->_platform->_auth->owner_id` as PubNub userID

@coxlr Many thanks.

**Comment by coxlr** [comment]
@tylerlong thanks for the update. I had to change from using ```setUserId``` to ```setUuid``` to make it compatible with PubNub v4. I believe both should work as both methods are documented https://www.pubnub.com/docs/sdks/php/api-reference/configuration#set-userid and the tests successfully passed using v4 and v6. I also fully tested independently, and also using my package that requires this package https://github.com/coxlr/laravel-ringcentral

I will update the ID to use ```subscription->_platform->_auth->owner_id``` and get those changes committed shortly.

Thanks again!

**Comment by coxlr** [comment]
@tylerlong I've updated the setUuid function to now set the PubNub userId as ```$this->_platform->auth()->data()['owner_id']```

I have checked the PubNub code and v4 uses ```setUuid``` and does not have a ```setUserId``` function. The ```setUserId``` was introduced in v6 which also still includes the ```setUuid```  function and both functions set the ```uuid``` which is returned in the both the ```getUserId``` function (https://github.com/pubnub/php/blob/a57143359fa8ce81c273a8aaf54e714cb012532d/src/PubNub/PNConfiguration.php#L262) and ```getUuid``` function.  Therefore, I have kept the ```setUuid``` so that it will be backwards compatible and not introduce and breaking change. I tested using both v4 and v6 and the Uuid/UserId is successfully set and returned using either version.

I have tested this change locally using v4 and v6 and also Laravel 9 and Laravel 10 via my package, and all tests pass and work as expected.

Let me know if you need me to do anything else.
Thanks!

**Comment by tylerlong** [comment]
@coxlr  Many thanks. I will merge and publish new version.

**Comment by tylerlong** [comment]
@embbnux  I see you released the last version, what is the process to release a new version?

**Comment by tylerlong** [comment]
I think I've published it successfully, just update the version number and create a new release.

Now the latest version is 2.3.6: https://packagist.org/packages/ringcentral/ringcentral-php

**Pull request merged**
