### PR TITLE
Fixes to readme.md documentation

### PR DESCRIPTION
**Pull request by ITJamie**
I have made some fixes in the documentation that are calling functions that dont exist

### CODE REVIEW

**Comment by ITJamie** [comment]
Checks have been marked as failed because of the following non related error in travis ci "Warning: This development build of composer is over 30 days old. It is recommended to update it by running "/home/travis/.phpenv/versions/5.4/bin/composer self-update" to get the latest version."

**Comment by kirill-konshin** [comment]
I will look into CI failure in the next few days and merge your PR. In the mean time may I ask you to squash your commits into one.

**Comment by kirill-konshin** [comment]
```$sdk->Platform()``` should be ```$sdk->platform()``` (lower case)

**Comment by kirill-konshin** [comment]
I have updated `composer.json` to have `satooshi/php-coveralls` of version 1.0.0, so now CI is passing successfully.

**Comment by bdeanindy** [comment]
@kirill-konshin is this PR ready for merge after your review sir?

**Comment by kirill-konshin** [comment]
When this https://github.com/ringcentral/ringcentral-php/pull/16#issuecomment-170661792 will be fixed -- yes.

**Pull request closed without merging**
